[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[[redirects]]
  from = "/"
  to = "/Sistema de filtros.html"
  status = 302

[[redirects]]
  from = "/*"
  to = "/Sistema de filtros.html"
  status = 404

[build.environment]
  NODE_VERSION = "18"